name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Stage
        run: echo "Building Application..."

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Stage
        run: echo "Running Tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deployment Stage
        run: echo "Deploying Application..."